version: "3"

services:
    redis:
        image: redis
        restart: always
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - 6379:6379

    redis-commander:
        image: rediscommander/redis-commander
        restart: always
        environment:
          - REDIS_HOSTS=local:redis:6379
        ports:
          - "8081:8081"

    providers-api:
        build:
            context: ./
            dockerfile: './Dockerfile.providers'
        ports: 
            -   3000:3000
            
    webhooks-api:
        build:
            context: ./
            dockerfile: './Dockerfile.webhooks'
        environment:
            REDIS_URL: 'redis://redis:6379'
            CHOKIDAR_USEPOLLING: 'true'
            CHOKIDAR_INTERVAL: 1000
        ports:
            -   4000:4000

        depends_on:
            - redis

    callback-api:
        build:
            context: ./
            dockerfile: './Dockerfile.callback'
        ports: 
            -   5000:5000
