version: "3"

services:
    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379

    providers-api:
        build:
            context: '.'
            dockerfile: './Dockerfile.providers'
        ports: 
            - 3000:3000
            
    webhooks-api:
        build:
            context: '.'
            dockerfile: './Dockerfile.webhooks'
        environment:
            REDIS_URL: redis:6379
        ports:
            - 4000:4000
        depends_on:
            - redis
